### ISSUE TITLE
Recent version stopped working on Ubuntu 18.10

### ISSUE THREAD

**Issue by sojusnik** [leonardo-bartoli/gnome-shell-extension-Recents#20]
When clicking on the settings this appears:

```
TypeError: ExtensionUtils.getSettings is not a function

Stack trace:
  @/home/sojusnik/.local/share/gnome-shell/extensions/Recents@leonardo.bartoli.gmail.com/settings.js:6:17
  @/home/sojusnik/.local/share/gnome-shell/extensions/Recents@leonardo.bartoli.gmail.com/prefs.js:12:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
```
I'm running Gnome 3.30 with Ubuntu 18.10.

**Comment by leonardo-bartoli** [comment]
Are you able to try the latest version from  preferences-fix branch?

**Comment by sojusnik** [comment]
The preferences work again, but I can't enable the extension now – [error appears](https://i.imgur.com/cyM8fnW.png).

**Comment by leonardo-bartoli** [comment]
Unfortunately I do not currently have access to a machine with Ubuntu 18.10, can you provide a complete error log? (through journalctl for example)

**Comment by miguelsan** [comment]
Same here:
```
TypeError: ExtensionUtils.getSettings is not a function

Stack trace:
  @/home/miguel/.local/share/gnome-shell/extensions/Recents@leonardo.bartoli.gmail.com/settings.js:6:17
  @/home/miguel/.local/share/gnome-shell/extensions/Recents@leonardo.bartoli.gmail.com/prefs.js:12:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  ```

From `journalctl`:
  ```
may 03 15:38:11 y0g4mc gnome-shell[16477]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
may 03 15:38:11 y0g4mc gnome-shell[16477]: The offending signal was destroy on ClutterClone 0x55df233abbc0.
may 03 15:38:11 y0g4mc org.gnome.Shell.desktop[16477]: == Stack trace for context 0x55df21ad5200 ==
may 03 15:38:11 y0g4mc gnome-shell[16477]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
may 03 15:38:11 y0g4mc gnome-shell[16477]: The offending signal was destroy on ClutterClone 0x55df233ab860.
may 03 15:38:11 y0g4mc gnome-shell[16477]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
may 03 15:38:11 y0g4mc gnome-shell[16477]: The offending signal was destroy on ClutterClone 0x55df233ab500.
may 03 15:38:11 y0g4mc gnome-shell[16477]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
may 03 15:38:11 y0g4mc gnome-shell[16477]: The offending signal was destroy on StLabel 0x55df27520e80.
may 03 15:38:11 y0g4mc gnome-shell[16477]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
may 03 15:38:11 y0g4mc gnome-shell[16477]: The offending signal was destroy on StBin 0x55df23fda6f0.
  ```

**Comment by iliman** [comment]
The same on Ubuntu 18.04

**Comment by leonardo-bartoli** [comment]
The changes needed for latest gnome shell version break older compatibility with older shell versions. I have to restrict compatible versions
